### ISSUE TITLE
Проблем код пресловљавања веб странице на n1info.rs

### ISSUE THREAD

**Issue by miljanuscumlic** [eevan78/translit#4]
Приликом покушаја пресловљавања веб странице https://n1info.rs/magazin/lifestyle/do-tunisa-ove-godine-letovima-iz-beograda-ali-i-iz-nisa/ долази до појаве грешке.

Кораци за репродукцију:
1. Сними се страница на локални фајл систем. У мом случају као tunis_lat.html
2. Компајлира се транслит програм према инструкцијама са README.md
3. Покрене се пресловљавање. У мом случају комадом на Убунту Линуксу:
`./translit -html -l2c <../test/translit/tunis_lat.html >../test/translit/tunis_to_cir.html`
4. Добија се грешка:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.traverseNode(0xc00029a3f0)
	/translit.go:973 +0x6a5
main.traverseNode(0xc00029a380)
	/translit.go:993 +0x225
main.traverseNode(0xc00029a2a0)
	/translit.go:993 +0x225
main.traverseNode(0xc000299ab0)
	/translit.go:993 +0x225
main.traverseNode(0xc0002999d0)
	/translit.go:993 +0x225
main.traverseNode(0xc0002997a0)
	/translit.go:993 +0x225
main.traverseNode(0xc000299490)
	/translit.go:993 +0x225
main.traverseNode(0xc0002993b0)
	/translit.go:993 +0x225
main.traverseNode(0xc000298850)
	/translit.go:993 +0x225
main.traverseNode(0xc000298770)
	/translit.go:993 +0x225
main.traverseNode(0xc0001e9ea0)
	/translit.go:993 +0x225
main.traverseNode(0xc00011b110)
	/translit.go:993 +0x225
main.traverseNode(0xc00011b030)
	/translit.go:993 +0x225
main.main()
	/translit.go:1011 +0x1cf
```

**Comment by eevan78** [comment]
Проблем је решен у издању v0.3.0
